### ISSUE TITLE
Persistent mobile toolbar

### ISSUE THREAD

**Issue by seaneking** [SimplaElements/sm-ui-toolbar#13]
We can't have the popup-on-highlight toolbar on mobile, as we can't override the native toolbar on both iOS and Android. Instead we should have a persistent formatting bar across the top of the viewport that pops into view whenever the user is focussed on a simpla-text (or wherever the toolbar is used). The native one will still popup when the user highlights, but that's fine. Native controls work, they just don't have enough (links, etc).

Could be done as part of #9 ?

**Comment by bedeoverend** [comment]
So I was digging through Slate's source awhile back and came across [this line](https://github.com/ianstormtaylor/slate/blob/master/src/components/content.js#L641). Looks like the CSS `-webkit-user-modify: read-write-plaintext-only;` should be able to hide the formatting bar that comes up i.e. so we can supply our own.

**Comment by seaneking** [comment]
On Chrome/Android and Safari/iOS?

Even so, is that wise? Would the user expect their toolbar (eg: for copy/paste/lookup)? Seems the more responsible thing to do would be provide our own formatting bar.

**Comment by bedeoverend** [comment]
Re: platforms, yeah I think so.

I'm not sure - I think we might need to, given consistency across platforms and control over what's presented to the user. Ideally we'd use native, but the differences across browsers might make that difficult, and not sure how smooth it'll feel splitting the UI across different toolbars. Also means that future builds / updates to browsers e.g. changing the toolbars, won't cause us (as many) headaches.

I get both sides though, just flagged it so we know we have the opportunity.
