### ISSUE TITLE
Toolbar should be able to (optionally) force formatting styles

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/sm-ui-toolbar#2]
If the styles of an element are set via a source outside of toolbar e.g. user stylesheet, then that tool now has no affect - whether applying or removing the styling. 

An example of this is with the default styling of a link - a link is underlined by default, so underline button on toolbar becomes active, however clicking it does nothing, as there's no `u` element for the toolbar to unwrap, the underline is intrinsically linked with link in this sense.

**Comment by seaneking** [comment]
this is related to simpla-text, not the toolbar. Closing
